### ISSUE TITLE
"Home" button does not respect web_prefix config parameter

### ISSUE THREAD

**Issue by cpandar** [webgovernor/pykwiki#11]
Hi, I am enjoying pykwiki's simplicity so far. Thanks for all your effort.

I am deploying my site on a page that is not the webserver's base page, e.g., my site sits at:
  http://webserver.com/~mysite/

To have everything linked correctly, I use the web_prefix parameter in config.yaml:
  web_prefix: '/~mysite'

Mostly this works great. However, the "Home" button that is generated by default seems to still point to '/' (i.e., http://webserver.com/)

Is there an alternate configuration option that would fix this behavior?

Thanks in advance.

**Comment by cpandar** [comment]
I should note that this is the default "Home" link. If I add my own Home link in links.yaml, I end up having two "Home" links

**Comment by webgovernor** [comment]
Hi Cpander, would you mind telling me which theme you're using? I'll bet that the home link is hard coded as "/" into the theme instead of using the appropriate value.

**Comment by cpandar** [comment]
Thanks, you are correct. I was using the "default" theme and the home link is hardcoded in that theme. For now, I just hardcoded my fix.

**Comment by webgovernor** [comment]
I'm trying to think of a good way to handle this. Here's what I have rollin' around in my noodle:

1. Update the existing themes to use `conf.web_prefix` in `menu.html`
2. Update the existing themes to optionally hide the first link, like in the `options.yaml` file for a theme, have `show_home_link: Bool` or something, and still do number 1. 
3. Just remove it entirely. Existing sites will not be impacted unless they install a new theme. 

What do you think?
