### ISSUE TITLE
Error plantuml extension: TypeError: makeExtension() takes exactly 0 arguments (1 given)

### ISSUE THREAD

**Issue by cinxgler** [webgovernor/pykwiki#12]
Hi,

When pykwiki.ext.uml extension is included in the config.yml i get this error running `pykwiki cache -f
`

    Reading configuration from config.yaml
    ========================================
    Caching source posts...
    No post config specified for index.md
    Caching: index.md
    Traceback (most recent call last):
      File "/usr/local/bin/pykwiki", line 254, in <module>
        command_cache(args)
      File "/usr/local/bin/pykwiki", line 136, in command_cache
        num_cached = ctrl.cache_posts(plist, force=force)
      File "/usr/local/lib/python2.7/dist-packages/pykwiki/core.py", line 262, in cache_posts
        pg.save()
      File "/usr/local/lib/python2.7/dist-packages/pykwiki/core.py", line 727, in save
        tt = self.target_text
      File "/usr/local/lib/python2.7/dist-packages/pykwiki/core.py", line 831, in target_text
        extensions=conf.markdown_exts)
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 410, in markdown
        md = Markdown(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 137, in __init__
        configs=kwargs.get('extension_configs', {}))
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 163, in registerExtensions
        ext = self.build_extension(ext, configs.get(ext, []))
      File "/usr/lib/python2.7/dist-packages/markdown/__init__.py", line 211, in build_extension
        return module.makeExtension(configs.items())
    TypeError: makeExtension() takes exactly 0 arguments (1 given)

I'm using python-markdown 2.4-1 (ubuntu 14.04 package) and pykwiki 1.1.2 (pip install)

Any help is appreciated.

- CMM

**Comment by webgovernor** [comment]
Hey Cinxgler. 

Can you post your `config.yaml` file?

**Comment by cinxgler** [comment]
This is the content:
    blurb_max: 50
    date_format: '%Y-%m-%d'
    home_page: index
    markdown_exts:
      - codehilite
      - toc
      - tables
      - pykwiki.ext.tpl
      - pykwiki.ext.post
      - pykwiki.ext.uml
    postlist:
      max_pages: 5
      order_field: mtime
      order_type: descending
      per_page: 2
      post_type: preview
    rss_max_entries: 20
    site:
      author: Subdirección Técnica de Recursos Tecnológicos - STRT
      base_url: ''
      description: Documentación de sistemas de Información grupo I+D+I
      keywords: idu, openerp, idu
      title: IDU - STRT[I+D+I]
    source_ext: .md
    theme: idu
    time_format: '%H:%M:%S'
    timestamp_format: '%Y-%m-%d %H:%M'
    web_prefix: ''

**Comment by webgovernor** [comment]
Thanks! I'm unable to reproduce with my UML example. Could you post your UML extension code? 

Here's what I'm using:
```
{uml}
Alice -> Bob: Connection
Bob -> Marge: Another connection
note left: This is just a note
{enduml}
```

**Comment by webgovernor** [comment]
Alright, I was able to get the index example you sent me working (I removed everything but the UML). 

Here: http://pykwiki.nullism.com/umltest.html

However, I'm running Python Markdown 2.6.1 which has some performance benefits. 

Are you able to update to a more recent version of Markdown? 

```
sudo pip install markdown --upgrade
```

**Comment by cinxgler** [comment]
It works ok using the latest pip markdown package.

Thanks.

**Comment by webgovernor** [comment]
Glad you got it working! I'm removing that UML testing link now.
