### ISSUE TITLE
ImportError: No module named 'jinja_filters'

### ISSUE THREAD

**Issue by passionaqua** [webgovernor/pykwiki#8]
Hi all,

I've recently done an installation of Arch linux, but when I wanted to install (a simple pip install pykwiki) and then use Pykwiki, I have that kind of error :

```
[adrien@ArchPaw site_du_projet]$ pykwiki cache -f
Reading configuration from /home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/config.yaml
========================================
Caching source posts...
Caching: index.md
Saving to: /home/adrien/Espace_Dev/Projets-multi/AnotherNotebook/site_du_projet/docroot/index.html
Traceback (most recent call last):
  File "/usr/bin/pykwiki", line 254, in <module>
    command_cache(args)
  File "/usr/bin/pykwiki", line 136, in command_cache
    num_cached = ctrl.cache_posts(plist, force=force)
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 262, in cache_posts
    pg.save()
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 729, in save
    html = render_theme_template(conf.post_tpl, post=self)        
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 27, in render_theme_template
    env = set_jinja_filters(env)
  File "/usr/lib/python3.4/site-packages/pykwiki/core.py", line 16, in set_jinja_filters
    import jinja_filters
ImportError: No module named 'jinja_filters'
```

I've tried to do a `sudo pip install --upgrade pykwiki` but nothing change :( 

Is there a solution?

**Comment by passionaqua** [comment]
I would like to inform you that my Python's version is 3.4.2 (from `python --version`) and my Jinja2' version is 2.7.3 (from `pip show Jinja2`).
I don't really understand why I have this error :/

**Comment by webgovernor** [comment]
Hi there! Sorry for the delay in response.

Can you please run the following to help me track this down a little bit:

    python3
    >>> import pykwiki
    >>> pykwiki.__file__
    >>> import pykwiki.jinja_filters

I just need to see the output of that code. Thanks for your time!

**Comment by webgovernor** [comment]
Aha! Nevermind. I think I found the issue. I'll be pushing a fix to the repo and creating a new build in a bit.

**Comment by webgovernor** [comment]
pykwiki 1.1.0 (which contains this fix) should be available on Python.org shortly.

    pip install --upgrade pykwiki

**Comment by passionaqua** [comment]
Thanks, but I still have a problem. I'll publish a new issue for it.
